import React from 'react';
import Head from 'next/head';

import styles from '~/styles/Home.module.scss';

const Home: React.FC = () => (
  <div className={styles.container}>
    <Head>
      <title>Generate Social Info | Social Linker</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}>
      <h1 className={styles.title}>
        Welcome to <a href="https://nextjs.org">Next.js!</a>
      </h1>
    </main>
  </div>
);

export default Home;
