import React, {useEffect} from 'react';
import {NextPage} from 'next';
import Head from 'next/head';
import {useRouter} from 'next/dist/client/router';
import {Typography} from '@material-ui/core';
import {makeStyles} from '@material-ui/core/styles';

import {SocialPage} from '~/typings';
import {decryptText} from '~/utils/encryption';

type Props = {
  pageData: SocialPage | null;
};

const Page: NextPage<Props> = ({pageData}) => {
  const router = useRouter();
  const styles = useStyles();

  // Just in case `getInitialProps` can't handle this,
  useEffect(() => {
    if (!pageData) router.replace('/');
  }, [pageData, router]);

  if (!pageData) return null;

  return (
    <>
      <Head>
        <title>{pageData.title} | Social Linker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <Typography variant="h4" className={styles.title}>
          {pageData.title}
        </Typography>
        {!!pageData.desc && (
          <Typography className={styles.desc} component="span">
            {pageData.desc}
          </Typography>
        )}
      </div>
    </>
  );
};

Page.getInitialProps = ({query, res}) => {
  const {token} = query;
  try {
    const decryptedText = decryptText(token as string);
    const pageDataJSONString = Buffer.from(decryptedText, 'base64').toString();
    const pageData = JSON.parse(pageDataJSONString);
    return {pageData};
  } catch {
    res?.writeHead(301, {Location: '/'});
    res?.end();
    return {pageData: null};
  }
};

const useStyles = makeStyles(({spacing}) => ({
  container: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: spacing(12, 2),
  },
  title: {
    textAlign: 'center',
    marginBottom: spacing(2),
  },
  desc: {
    textAlign: 'center',
    marginBottom: spacing(4),
  },
}));

export default Page;
