import React, {useEffect, useMemo} from 'react';
import {NextPage} from 'next';
import Head from 'next/head';
import {useRouter} from 'next/dist/client/router';
import {Typography, Divider} from '@material-ui/core';
import {makeStyles} from '@material-ui/core/styles';

import {SocialPage} from '~/typings';
import {decryptText} from '~/utils/encryption';
import LinkButton from '~/components/LinkButton';

type Props = {
  pageData: SocialPage | null;
};

const Page: NextPage<Props> = ({pageData}) => {
  const router = useRouter();
  const randomColor1 = useMemo(
    () => `hsl(${Math.random() * 360}, 100%, 75%)`,
    [],
  );
  const randomColor2 = useMemo(
    () => `hsl(${Math.random() * 360}, 100%, 75%)`,
    [],
  );
  const styles = useStyles();

  // Just in case `getInitialProps` can't handle this,
  useEffect(() => {
    if (!pageData) router.replace('/');
  }, [pageData, router]);

  if (!pageData) return null;

  return (
    <>
      <Head>
        <title>{pageData.title} | Social Linker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.backdrop}>
        <div
          className={styles.backdropBall1}
          style={{background: randomColor1}}
        />
        <div
          className={styles.backdropBall2}
          style={{background: randomColor2}}
        />
      </div>
      <div className={styles.container}>
        <div className={styles.contentWrapper}>
          <Typography variant="h4" className={styles.title}>
            {pageData.title}
          </Typography>
          {!!pageData.desc && (
            <Typography className={styles.desc} component="span">
              {pageData.desc}
            </Typography>
          )}
          <Divider className={styles.divider} />

          {pageData.links.map(link => (
            <LinkButton key={link.value} url={link.value} />
          ))}
        </div>
      </div>
    </>
  );
};

Page.getInitialProps = ({query, res}) => {
  const {token} = query;
  try {
    const decryptedText = decryptText(token as string);
    const pageDataJSONString = Buffer.from(decryptedText, 'base64').toString();
    const pageData = JSON.parse(pageDataJSONString);
    return {pageData};
  } catch {
    res?.writeHead(301, {Location: '/'});
    res?.end();
    return {pageData: null};
  }
};

const useStyles = makeStyles(({spacing, breakpoints}) => ({
  backdrop: {
    zIndex: -1,
    position: 'fixed',
    width: '100vw',
    height: '100vh',
    opacity: 0.2,
  },
  backdropBall1: {
    content: '" "',
    position: 'absolute',
    left: '-10%',
    bottom: '-10%',
    width: '30%',
    aspectRatio: '1',
    borderRadius: '50%',
    animation: '$scale_animate_flip 5s infinite',

    [breakpoints.down('sm')]: {
      left: '-20%',
      bottom: '-15%',
      width: '50%',
    },

    [breakpoints.down('xs')]: {
      left: '-30%',
      bottom: '-10%',
      width: '60%',
    },
  },
  backdropBall2: {
    content: '" "',
    position: 'absolute',
    right: '-20%',
    bottom: '-10%',
    width: '50%',
    aspectRatio: '1',
    borderRadius: '50%',
    animation: '$scale_animate 5s infinite',

    [breakpoints.down('sm')]: {
      width: '70%',
    },

    [breakpoints.down('xs')]: {
      right: '-40%',
      bottom: '-5%',
      width: '90%',
    },
  },
  '@keyframes scale_animate': {
    '0%': {transform: 'scale(1)'},
    '50%': {transform: 'scale(1.1)'},
    '100%': {transform: 'scale(1)'},
  },
  '@keyframes scale_animate_flip': {
    '0%': {transform: 'scale(1.1)'},
    '50%': {transform: 'scale(1)'},
    '100%': {transform: 'scale(1.1)'},
  },
  container: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: spacing(12, 2),
  },
  contentWrapper: {
    display: 'flex',
    flexDirection: 'column',
    width: '40%',

    [breakpoints.down('md')]: {
      width: '50%',
    },

    [breakpoints.down('sm')]: {
      width: '70%',
    },

    [breakpoints.down('xs')]: {
      width: '100%',
    },
  },
  title: {
    textAlign: 'center',
    marginBottom: spacing(2),
  },
  desc: {
    textAlign: 'center',
    marginBottom: spacing(4),
  },
  divider: {
    alignSelf: 'center',
    width: '80%',
    margin: spacing(4, 0),
  },
  linkButton: {
    width: '100%',
  },
}));

export default Page;
